### PR TITLE
Adding support to for multi-line variables.

### PR DESCRIPTION
**Pull request by ghost**
I am using a named babel src block to generate a list of headers for me to reuse with multiple restclient src blocks. `restclient-mode` supports multi-line variables like this:
```
:myHeaders = <<
Authorization: Bearer ....
transaction_id: 1234-1234-1234
Content-Type: application/json
#
```
The problem I ran into was that the current variable definition implementation only allows for single line variables. This PR moves the variable definition to the multi-line pattern, which works just as well for single line variables.

---
In case you're curious (or the context is helpful) this is the basic idea of what I'm doing:
```
#+NAME: myHeaders
#+BEGIN_SRC bash
echo -n "Authorization: Bearer ....
transaction_id: 1234-1234-1234
Content-Type: application/json"
#+END_SRC

* API Calls
:PROPERTIES:
:header-args:restclient :var myHeaders=myHeaders()
:END:

Call 1:
#+BEGIN_SRC restclient
GET /api/i/want/to/call
:myHeaders
#+END_SRC

Call 2:
#+BEGIN_SRC restclient
GET /second/api/i/want/to/call
:myHeaders
#+END_SRC
```

### CODE REVIEW

**Comment by alf** [comment]
Thank you, this is a nice addition. I also appreciate your rationale and example.

**Comment by ghost** [comment]
Thanks!

**Comment by pszynk** [comment]
Sorry to necrobomb this thread but did you considered a possibility to use multi-line variables inside `#+PROPERTY:` header?

```
#+PROPERTY: header-args:restclient  :var common_header=<
#+PROPERTY: header-args:restclient+ Authorization: Bearer ....
#+PROPERTY: header-args:restclient+ transaction_id: 1234-1234-1234"
#+PROPERTY: header-args:restclient+ Content-Type: application/json
#+PROPERTY: header-args:restclient+ #
```

Either way this is a nice solution, so thanks for that. For me adding `:results output silent` was helpful.

```
#+NAME: myHeaders :results output silent
#+BEGIN_SRC bash
echo -n "Authorization: Bearer ....
transaction_id: 1234-1234-1234
Content-Type: application/json"
#+END_SRC
```

**Comment by ghost** [comment]
@pszynk This is out of scope for this project. Parsing out header args and any `#+KEYWORD:` is the responsibility of org-mode. This (as with all such ob lang packages) is just leveraging APIs provided by org-mode. That being said, something similar to what you propose can actually work (much to my surprise).

First, note that when setting a `:var` you must wrap it in double quotes, so generally that looks like `:var name="value"`. Taking that we can generate a multiline header on one line like so
```
#+PROPERTY: header-args:restclient  :var common_header="< \nAuthorization: Bearer ... \ntransaction_id: 1234-1234-1234 #"
```

But we can do better, modifying your example by adding double quotes and newlines the following worked for me
```
#+PROPERTY: header-args:restclient  :var common_header="< \n
#+PROPERTY: header-args:restclient+ Authorization: Bearer ....  \n
#+PROPERTY: header-args:restclient+ transaction_id: 1234-1234-1234  \n
#+PROPERTY: header-args:restclient+ Content-Type: application/json  \n
#+PROPERTY: header-args:restclient+ #"
```

You can of course do this in property drawers too (e.g. the following type of thing works too)
```
* Test
:PROPERTIES:
:header-args:bash: :var test="Hello
:header-args:bash+: World" 
:END:

#+begin_src bash 
echo "$test"
#+end_src
```


We could probably make something like this work (and definitely in scope of this project):
```
#+NAME: headers
- Header: val
- Header2: val2
  
#+begin_src restclient :var common_header=headers() 
GET https://google.com
:common_header
#+end_src
```
We'd just need to handle for list values for a `:var` instead of just strings in `org-babel-execute:restclient`.

**Comment by pszynk** [comment]
@tylerware thanks a lot for the explanation. You are right about the scope of course. I was trying to reach your solution using standard `org-mode` syntax, just couldn't get it right, so thanks again.

Still could you clarify one thing?  

```
#+PROPERTY: header-args:restclient  :var common_header="< \n
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
```
what is the purpose of `<` sign? In fact It doesn't work for me when it's present.

This works:
```
#+PROPERTY: header-args:restclient  :var common_header=
#+PROPERTY: header-args:restclient+ "Authorization: Bearer ....  \n
#+PROPERTY: header-args:restclient+ transaction_id: 1234-1234-1234  \n
#+PROPERTY: header-args:restclient+ Content-Type: application/json  \n
#+PROPERTY: header-args:restclient+ #"
```

And the most readable that worked is:
```
#+PROPERTY: header-args:restclient  :var common_header="\
#+PROPERTY: header-args:restclient+ Authorization: Bearer ....  \n
#+PROPERTY: header-args:restclient+ transaction_id: 1234-1234-1234  \n
#+PROPERTY: header-args:restclient+ Content-Type: application/json  \n
#+PROPERTY: header-args:restclient+ #"
```


It looks like there has to be no prefix whitespace in the header variable, otherwise it is considered a body.

**Comment by ghost** [comment]
> what is the purpose of `<` sign? In fact It doesn't work for me when it's present.

That is just an error on my part - I copied your example and just edited without thinking about it. The `<` is not needed, also I think the `#` can be left off the end. The only syntactical reason for either is when setting a multiline var within restclient mode. Anyway, since those characters are added in `org-babel-execute:restclient` I can't see any reason for them here.

I didn't test the exact solution w/ restclient mode as I didn't have an API readily available to hit, so I just verified the basic org-mode functionality -- sorry for the confusion. Good to know about the whitespace at the front too! 

Also, thanks for necrobombing. I got to learn something new about org-mode and it's fun to be surprised that things actually "just work" sometimes. That's emacs for you.

**Pull request merged**
